services:
  - type: web
    name: bg-removal-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn background_remover_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: SECRET_KEY
        value: your-super-secret-production-key
      - key: MONGODB_URI
        value: mongodb+srv://<username>:<password>@<cluster-name>.mongodb.net/?retryWrites=true&w=majority
